Advanced Search
tsg-ut/slack-patron pull request #21
Opened 2021-06-16 20:35 UTC by Yosshi999

![image](https://user-images.githubusercontent.com/8027142/122289455-b3166780-cf2d-11eb-88ad-b508e76e96ce.png)

2021-06-17 03:07 UTC, hakatashi commented
！？

2021-06-17 12:05 UTC, hakatashi requested changes

2021-06-17 12:05 UTC, hakatashi commented on viewer/front/components/AdvancedSearchWindow.less
> +.configure-window {
このあたりのCSSはConfigureWindowと共通だと思うので、なるべくConfigureWindowと共通してる部分をくくりだしてComponentとして切り出したいですね～ つまり新しいModalみたいなComponentを用意して、

```
class AdvancedSearchWindow extends React.Component {
  render() {
    return (
      <Modal>
        <いろいろ>
      </Modal>
    );
  }
}
```

みたいな感じにしたい。まあ難易度高いと思うのでこのプルリク内でやらなくても良いです

2021-06-17 14:14 UTC, Yosshi999 commented on viewer/front/components/AdvancedSearchWindow.less
> +.configure-window {
これは諦めます...

2021-06-17 14:19 UTC, Yosshi999 commented
![image](https://user-images.githubusercontent.com/8027142/122414989-7f395180-cfc2-11eb-9111-076fcc06316e.png)

2021-06-18 15:03 UTC, hakatashi approved these changes
![LGTM](https://image.lgtmoon.dev/130905)

2021-06-18 15:04 UTC, merged